# cloudbuild.yaml with postgres and sourceclear integration 
secrets:
- kmsKeyName: projects/cicd-183109/locations/global/keyRings/srcclr_api_token_keyring/cryptoKeys/srcclr_api_token_key
  secretEnv:
    SRCCLR_API_TOKEN: CiQAUdQPv1dOkXtrIzFoSXHDLhLYFDLZ2xJATTsowWb7d6feSz8SyQMALwPDuy/U6KAEaqnd8La+e8p5SHomndmF5zYBw7/YFkxWFpHtK98odskgs3nuftaQWtaawUgxkq/LrvcTxA6XqioOwRt156BnLNZrAyGQ4vK6s1eNuK2/Bui5Q0M9LYl7ERG1vJbAGff8wwKOV9mDTuDHd/3/6ZYiDwlvNMF6i7toB21+fjOLt/pN7AmoIYemewa3wLWX2yUuQK5J87YsmPwGY16BJLn6ZeYBfl+sjPGd/vfdzGjyxjLOaJKkjVTSka/UMWFmPVGhc2jsfy3Qt5qKCHXRapFw4rZrzrM2hAdCL8dm5QkCffD4keRnB8DGHY3bT+rd0yzWScy7ETTYQrSlK9UZJCN0CBGcRQDLCcnAppE8/Qr1IrCpcUVFy5b2j72RV5wwGF70ety8kjqc/PmG6O5XiUEe63UeoV0TsEQKKIHEK3XJ5NIS0AigIblCtRME9J5gONVVjWaBCyagxv83yLvjQW20HB9BYsPBv9bzIztLHwMt9ayiTtXOor7ZmlH2M6lGxj58aag2MvWJsdETS0BimjLGQMDRDVxtvTeNIKTU0wFlbBAmsreGoL4Ioc3MiGyYorRWDE4odtz1xY6uZT7qc5kW
    
steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'chmod 755 ./vertex-container-build-with-postgres-sclr.sh; ./vertex-container-build-with-postgres-sclr.sh']
  secretEnv: ['SRCCLR_API_TOKEN']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/vertx-template:$REVISION_ID", "-t", "gcr.io/$PROJECT_ID/vertx-template:latest", "."]
images:
  - 'gcr.io/$PROJECT_ID/vertx-template-postgres:$REVISION_ID'
  - 'gcr.io/$PROJECT_ID/vertx-template-postgres:latest'
